name: ClothingShop CD

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          touch .env 
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env 
          echo SECRET_COOKIE_PASSWORD=${{ secrets.SECRET_COOKIE_PASSWORD }} >> .env
      - run: npm i
      - run: npm run build --if-present
      - run: pm2 restart clothing-shop -s
